title: The Nature of Code (JS)

description: >
  Exploring Daniel Shiffman's Processing book, but with Javascript

baseurl: "/the-nature-of-code.js" # the subpath of your site, e.g. /blog/
url: "http://lpil.github.io" # the base hostname & protocol for your site

markdown: kramdown
sass_dir: _scss

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
